### ISSUE TITLE
Cross device soft-links are turned to hard-links on taking a snapshot.

### ISSUE THREAD

**Issue by musically-ut** [data-workspaces/data-workspaces-core#36]
Unsure whether this is a bug but when I try to add a local soft-link as a `local-file` resource, taking a snapshot fails with the following error:

```
$ dws snapshot
snapshot of /path/to/repo, tag=None, message=
Traceback (most recent call last):
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/dataworkspaces/__main__.py", line 15, in main
    cli()
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/dataworkspaces/dws.py", line 309, in snapshot
    snapshot_command(workspace_dir, ns.batch, ns.verbose, tag, message)
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/dataworkspaces/commands/snapshot.py", line 372, in snapshot_command
    "taken snapshot of workspace", batch=batch, verbose=verbose)
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/dataworkspaces/commands/actions.py", line 309, in run_plan
    action.run()
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/dataworkspaces/commands/snapshot.py", line 59, in run
    (compare_hash, restore_hash) = self.resource.snapshot()
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/dataworkspaces/resources/local_file_resource.py", line 79, in snapshot
    h = hashtree.generate_size_signature(self.rsrcdir, self.local_path, ignore=self.ignore)
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/dataworkspaces/resources/hashtree.py", line 249, in generate_size_signature
    return generate_hashes(rsrcdir, localpath, ignore=ignore, hash_fun=compute_size)
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/dataworkspaces/resources/hashtree.py", line 171, in generate_hashes
    h = t.write()
  File "/home/utkarshu/miniconda3/lib/python3.7/site-packages/dataworkspaces/resources/hashtree.py", line 114, in write
    os.rename(tmpname, objfile)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpdhllqho4' -> '/path/to/repo/.dataworkspace/file/intermediate-data/processed/032cb5c0ac5d5513227899024ee7126e844a12f2'

Aborting due to unexpected exception: OSError(18, 'Invalid cross-device link')
````

Without adding the local soft-link as a local-file resource, and only keeping the target as a local-file resource causes complaints that I cannot write output to the soft-linked folder as it is not an intermediate data resource.

Unsure what the best way to fix it would be, other than trying to create soft-links while taking snapshots too?

**Comment by jfischer** [comment]
I think this is just another case of a problem we've seen in the past where os.rename() does not work across file systems. Depending on how your system is set up, this could bite you (e.g. if you have /tmp on a separate filesystem from your current directory). I've replaced all instances of os.rename() in our codebase with a safe one that first tries the traditional rename and then does a copy followed by delete of the original if that fails.

I've uploaded version 1.0.7 to PyPi including this fix. If you still see a problem, reopen the bug and let me know. Thanks!
