### ISSUE TITLE
dws should work with a primary branch named "main"

### ISSUE THREAD

**Issue by jfischer** [data-workspaces/data-workspaces-core#75]
Github changed their branch naming convention - if you create a new repository, the primary branch is now "main", not "master". We need to adjust DWS accordingly.  Here are the known situations where this makes a difference:

* dws init should handle main as the branch
* in the git subdirectory resource, it is expecting the branch name to be master, we should allow main
* in git resources, we should handle main as a default case.

**Comment by jfischer** [comment]
Here' one problem I found when trying to add a resource:
```
dws --verbose add git --role=code ./git_analytics_tools/
Please enter a short, unique name for this resource [git_analytics_tools]:
/usr/bin/git ls-files --error-unmatch /Users/jfischer/code/metagraph/git_analytics_tools [run in /Users/jfischer/code/metagraph]

/usr/bin/git exited with 1
/usr/bin/git config --get remote.origin.url [run in /Users/jfischer/code/metagraph/git_analytics_tools]
/usr/bin/git branch [run in /Users/jfischer/code/metagraph/git_analytics_tools]
* main

Traceback (most recent call last):
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/dataworkspaces/__main__.py", line 15, in main
    cli()
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/dataworkspaces/dws.py", line 598, in git
    add_command("git", role, name, workspace, path, branch, read_only, export, imported)
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/dataworkspaces/commands/add.py", line 29, in add_command
    workspace.add_resource(name, scheme, role, *args)
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/dataworkspaces/backends/git.py", line 319, in add_resource
    r = super().add_resource(name, resource_type, role, *args, **kwargs)
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/dataworkspaces/workspace.py", line 294, in add_resource
    r = f.from_command_line(role, name, self, *args, **kwargs)
  File "/Users/jfischer/anaconda3/envs/metagraph/lib/python3.8/site-packages/dataworkspaces/resources/git_resource.py", line 658, in from_command_line
    raise ConfigurationError(
dataworkspaces.errors.ConfigurationError: Requested branch 'master' is not available for git repository at /Users/jfischer/code/metagraph/git_analytics_tools

Configuration error: Requested branch 'master' is not available for git repository at /Users/jfischer/code/metagraph/git_analytics_tools
```

**Comment by jfischer** [comment]
This command will indicate the default branch:
```
git remote show origin | grep 'HEAD branch'
```
